version: '3.7'

services:

  tx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.tx
      args:
        INST_PORT: ${INSTANCE_PORT}
        EASARG_PORT: ${EAS_PORT}
        SVN_PORT: ${SNV_PORT}
    depends_on:
      - svn
      - db
    ports:
    - "${INSTANCE_PORT}:${INSTANCE_PORT}"
    - "${EAS_PORT}:${EAS_PORT}"

  db:
    image: oracle/database:12.2.0.1-ee
    volumes:
    - "./db/dump/0_tablespace.sql:/docker-entrypoint-initdb.d/setup/0.sql"
    - "./TX_dump.sql:/docker-entrypoint-initdb.d/setup/1.sql"
#    - "./db/dump/0_tablespace.sql:/docker-entrypoint-initdb.d/setup/0.sql"
#    - "./db/dump/setup.sql:/docker-entrypoint-initdb.d/setup/0.sql"
#    - "./db/dump:/docker-entrypoint-initdb.d/startup"
    environment:
      ORACLE_SID: TX
      ORACLE_PDB: TXDEV
      ORACLE_PWD: "123qwe"
    ports:
    - "1521:1521"

  svn:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.svnn
    ports:
    - "${SVN_PORT}:18080"
    - "3343:3343"
    - "4434:4434"

#volumes:
#  svndata:
