version: '3.7'

services:

  tx:
    env_file:
      - .env
    build:
      context: ./tranzaxis
      dockerfile: Dockerfile
      args:
        INST_PORT: ${INSTANCE_PORT}
        EASARG_PORT: ${EAS_PORT}
        SVN_PORT: ${SNV_PORT}
    depends_on:
      - svn
      - db
    ports:
    - "${INSTANCE_PORT}:${INSTANCE_PORT}"
    - "${EAS_PORT}:${EAS_PORT}"

  db:
    image: oracle/database:12.2.0.1-ee
#    volumes:
#    - "./db/dump/0_tablespace.sql:/docker-entrypoint-initdb.d/setup/0.sql"
#    - "./TX_dump.sql:/docker-entrypoint-initdb.d/setup/1.sql"
#    - "./db/dump/0_tablespace.sql:/docker-entrypoint-initdb.d/setup/0.sql"
#    - "./db/dump/setup.sql:/docker-entrypoint-initdb.d/setup/0.sql"
#    - "./db/dump:/docker-entrypoint-initdb.d/startup"
    environment:
      ORACLE_SID: TX
      ORACLE_PWD: "123123Qwe"
    ports:
    - "6622:1521"

  svn:
    env_file:
      - .env
    build:
      context: ./svn
      dockerfile: Dockerfile
    volumes:
    - svndata:/opt/csvn/data/repositories
    ports:
    - "18080:18080"
    - "3343:3343"
    - "4434:4434"

  manager:
    build:
      context: ./tranzaxis
      dockerfile: Dockerfile.manager
    volumes:
    - "./tranzaxis/manager/manager.conf:/tmp/manager/etc/manager.conf"

volumes:
  svndata:
