FROM openjdk:8

ENV MANAGER_NAME=manager_1_2_11_27_7
ENV MANAGER_FILE=${MANAGER_NAME}.zip

COPY ./manager/${MANAGER_FILE} /tmp/manager.zip

RUN apt-get install -y unzip && \
    unzip /tmp/manager.zip -d /tmp

COPY ./manager/manager.conf /tmp/manager/etc/manager.conf
COPY ./project /tmp/project